<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2TipMe\Module'             => __DIR__ . '/Module.php',
    'ZF2TipMe\SubstrFilter'       => __DIR__ . '/src/ZF2TipMe/SubstrFilter.php',
    'ZF2TipMe\TipController'      => __DIR__ . '/src/ZF2TipMe/TipController.php',
    'ZF2TipMe\TipForm'            => __DIR__ . '/src/ZF2TipMe/TipForm.php',
    'ZF2TipMe\TipService'         => __DIR__ . '/src/ZF2TipMe/TipService.php',
    'ZF2TipMe\Framework\TestCase' => __DIR__ . '/tests/ZF2TipMe/Framework/TestCase.php',
    'ZF2TipMe\SampleTest'         => __DIR__ . '/tests/ZF2TipMe/SampleTest.php',
);