A new gift has been received via your ZF2TipMe site!

Gift: <?php echo $this->tipItem['title']; ?>

Amount: $<?php echo sprintf('%.2f', $this->tipItem['amount']); ?>

<?php if (!empty($this->data['email'])) { ?>
From: <?php echo $this->data['email'];
} ?>


<?php if (!empty($this->data['message'])) { ?>
Message:
<?php echo $this->data['message'];
} ?>


Stripe Charge Id: <?php echo $this->charge['id']; ?>

https://manage.stripe.com/

Thanks for using ZF2TipMe!
https://github.com/cgmartin/ZF2TipMe