<div class="btn-group test-data-btns pull-right">
    <a class="btn btn-small dropdown-toggle" id="tipme-testdata-btn" data-toggle="dropdown" href="#">
        Fill Test Data
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" id="tipme-testdata-menu" role="menu" aria-labelledby="tipme-testdata-btn">
        <li><a class="test-data-btn" data-tip-cnum="4242424242424242" href="#">Visa</a></li>
        <li><a class="test-data-btn" data-tip-cnum="5555555555554444" href="#">MasterCard</a></li>
        <li><a class="test-data-btn" data-tip-cnum="378282246310005"  href="#">American Express</a></li>
        <li><a class="test-data-btn" data-tip-cnum="6011111111111117" href="#">Discover</a></li>
        <li><a class="test-data-btn" data-tip-cnum="30569309025904"   href="#">Diner's Club</a></li>
        <li><a class="test-data-btn" data-tip-cnum="3530111333300000" href="#">JCB</a></li>
        <li class="divider"></li>
        <li><a class="test-data-btn" data-tip-cnum="4000000000000101" href="#">CVC Failure</a></li>
        <li><a class="test-data-btn" data-tip-cnum="4000000000000341" href="#">Charge Failure</a></li>
        <li><a class="test-data-btn" data-tip-cnum="4000000000000002" href="#">Decline Failure</a></li>
        <li><a class="test-data-btn" data-tip-cnum="4000000000000069" href="#">Expiration Failure</a></li>
        <li><a class="test-data-btn" data-tip-cnum="4000000000000119" href="#">Processing Failure</a></li>
        <li class="divider"></li>
        <li><a href="https://stripe.com/docs/testing">Stripe Testing Docs</a></li>
    </ul>
</div>