<style>
    #tipForm, .controls .errors { display: none; }
</style>

<?php
$errors = $this->form->getMessages();
if (!empty($errors)) {
    ?><div class="tipme-errors alert alert-error">
        <h4>Error!</h4>
        <?php echo $this->formElementErrors($form); ?>
    </div><?php
} ?>

<?php echo $this->form()->openTag(
    $this->form->setAttribute('class', 'form-horizontal')
); ?>
<fieldset>
    <legend>Send a one-time gift
        <?php if ($this->form->isTestMode()) { ?>
            <?php echo $this->partial('zf2-tip-me/partial/test-data-btn'); ?>
        <?php } ?>
    </legend>

    <div class="control-group gift-group">
        <label class="control-label" for="tipOption">Choose a gift to give</label>
        <div class="controls">
            <?php echo $this->formRadio(
                $this->form->get('tipOption')->setLabelAttributes(array(
                    'class' => 'radio input-xlarge'
                ))
            ); ?>
            <span class="badge badge-important errors"></span>
            <span class="gift-image"></span>
        </div>
    </div>

    <div class="control-group cardNumber-group">
        <label class="control-label" for="cardNumber">Credit Card</label>
        <div class="controls">
            <input id="cardNumber" type="number" size="20" autocomplete="off" placeholder="XXXX XXXX XXXX XXXX"
                   required="required" class="no-spinner"/>
            <span class="badge badge-important errors"></span>
        </div>
    </div>

    <div class="control-group expiration-group">
        <label class="control-label" for="cardExpiryMonth">Expiration</label>
        <div class="controls">
            <input id="cardExpiryMonth" type="number" size="2" class="input-mini" min="1" max="12" required="required"
                   placeholder="MM" autocomplete="off"/>
            <span> / </span>
            <input id="cardExpiryYear" type="number" size="4" class="input-mini"  min="<?php echo date('Y') - 1; ?>"
                   max="<?php echo date('Y') + 30; ?>" required="required" placeholder="YYYY" autocomplete="off"/>
            <span class="badge badge-important errors"></span>
        </div>
    </div>

    <div class="control-group cardCvc-group">
        <label class="control-label" for="cardCVC">CVC</label>
        <div class="controls">
            <input id="cardCvc" type="number" size="4" autocomplete="off" min="100" max="9999" required="required"
                   class="input-mini no-spinner"/>
            <span class="card-images"></span>
            <span class="badge badge-important errors"></span>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <hr class="separator input-xlarge"/>
        </div>
    </div>

    <div class="control-group message-group">
        <label class="control-label">Message</label>
        <div class="controls">
            <?php echo $this->formTextarea(
                    $this->form->get('message')
                        ->setAttribute('class', 'input-large')
                        ->setAttribute('rows', 2)
                ); ?>
            <small class="help-inline">(Optional)</small>
            <div class="input-large">
                <small class="muted">200 characters maximum, text only.</small>
            </div>
        </div>
    </div>

    <div class="control-group email-group">
        <label class="control-label">Email Address<br>or Twitter Handle</label>
        <div class="controls">
            <?php echo $this->formText(
                    $this->form->get('email')
                        ->setAttribute('class', 'input-large')
                        ->setAttribute('placeholder', '@twitter')
                ); ?>
            <small class="help-inline">(Optional)</small>
            <?php echo $this->placeholder('tipMe')->emailNote; ?>
        </div>
    </div>

    <input type="hidden" name="stripeToken" id="stripeToken" value="" />

    <div class="control-group button-group">
        <div class="controls">
            <div>
                <button type="submit" class="btn btn-primary btn-submit">
                    Purchase gift for <?php echo $this->form->getRecipientName(); ?>
                    <span class="spin"></span></button>

            </div>
            <?php echo $this->placeholder('tipMe')->securityMessage; ?>
        </div>
    </div>
</fieldset>
</form>

<script type="text/javascript">
    $(function() {
        tipMe.init({
            stripePubKey   : '<?php echo $this->form->getStripePublishKey(); ?>',
            recipientName  : '<?php echo $this->form->getRecipientName(); ?>',
            formSelector   : '#<?php echo $this->form->getName(); ?>',
            confirmMessage : '<?php echo $this->confirmMessage; ?>'
        });
    });
</script>

