<?php
$this->inlineScript()
    ->appendFile($this->basePath() . '/tip-me-assets/js/spin.min.js')
    ->appendFile("https://js.stripe.com/v1/")
    ->appendFile($this->basePath() . '/tip-me-assets/js/tip-me.js');
$this->headLink()->appendStylesheet($this->basePath() . '/tip-me-assets/css/style.css');

$confirmMessage = 'Send a gift of ${{amount}} from your {{cardType}} to {{recipient}}?' .
                  '\nPressing "OK" will process the charge.';
?>

<div class="page-header">
    <h1>Enjoy my work?
</div>

<div class="row">
    <p class="span8">
        If you have used one of my open source projects and are feeling generous,
        donations of my favorite "coding fuel" are much appreciated.
    </p>
</div>

<noscript>
    <div class="alert alert-error">
        <h2>Error!</h2>
        <p>JavaScript must be enabled for this page to work.</p>
    </div>
</noscript>

<?php
// Email Note placeholder
$this->placeholder('tipMe_emailNote')->captureStart(); ?>
    <div class="input-large">
        <small class="muted">I will <strong>only</strong> use your email address to send a thank you message. No spam.</small>
    </div>
<?php $this->placeholder('tipMe_emailNote')->captureEnd(); ?>

<?php
// Security Message placeholder
$this->placeholder('tipMe_securityMessage')->captureStart(); ?>
    <div>
        <small class="muted secured">
            <i class="icon-lock"></i> Secured using
            <a href="https://stripe.com/us/help/faq#security-and-pci">Stripe</a>
            and 256-bit SSL encryption.
        </small>
    </div>
<?php $this->placeholder('tipMe_securityMessage')->captureEnd(); ?>

<?php echo $this->partial(
    'zf2-tip-me/partial/tip-form',
    array(
        'form'           => $this->form,
        'confirmMessage' => $confirmMessage,
    )
); ?>
