<?php
$this->headTitle('Tip me');
$this->headLink()->appendStylesheet($this->basePath() . '/tip-me-assets/css/style.css');
?>

<div class="page-header">
    <h1>You've made my day!</h1>
</div>

<?php
switch ($data['tipOption']) {
    case 'coffee':
        ?><p>Coffee is my staple drink.
        No fancy stuff - A <em>Bold Pick of the Day</em> is just what
        the internet ordered.
        </p><?php
        break;
    case 'redbull':
        ?><p>Red Bull shall give me wings. My coding agility has increased +17 points.</p><?php
        break;
    case 'music':
        ?><blockquote><p>
        "Music gives a soul to the universe, wings to the mind, flight to the imagination
        and life to everything."
        </p><small>Plato</small></blockquote><?php
        break;
}
?>

<p><img src="<?php echo $this->tipItem['img_src']; ?>"/></p>

<p>
    Thank you so much for your support.
</p>

<p>
    <strong>Your credit card has been charged $<?php echo sprintf('%.2f', $this->tipItem['amount']); ?>,
    and will show "<?php echo $this->statementDescriptor; ?>" on your statement.</strong>
</p>

<p>
    If you change your mind, please feel free to email
    me at <a href="mailto:<?php echo $this->adminEmail; ?>"><?php echo $this->adminEmail; ?></a>
    asking for a full refund.
</p>

